# Generated by Django 5.2.8 on 2026-02-24 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('training_samples', models.IntegerField(default=0)),
                ('validation_samples', models.IntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_model_metrics',
            },
        ),
        migrations.CreateModel(
            name='SimulationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_times', models.JSONField(default=list)),
                ('decision_patterns', models.JSONField(default=dict)),
                ('hesitation_points', models.JSONField(default=list)),
                ('time_based_score', models.FloatField(default=0.0)),
                ('accuracy_based_score', models.FloatField(default=0.0)),
                ('efficiency_score', models.FloatField(default=0.0)),
                ('common_mistakes', models.JSONField(default=list)),
                ('mistake_categories', models.JSONField(default=dict)),
                ('learning_progress', models.FloatField(default=0.0)),
                ('skill_improvement', models.JSONField(default=dict)),
                ('predicted_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='simulations.simulationsession')),
            ],
            options={
                'db_table': 'simulation_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_simulations', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('category_scores', models.JSONField(default=dict)),
                ('threat_type_scores', models.JSONField(default=dict)),
                ('learning_curve', models.JSONField(default=list)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('weak_areas', models.JSONField(default=list)),
                ('strong_areas', models.JSONField(default=list)),
                ('skill_levels', models.JSONField(default=dict)),
                ('recommended_scenarios', models.JSONField(default=list)),
                ('recommended_difficulty', models.CharField(default='beginner', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_performance',
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('date', models.DateField()),
                ('simulations_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time', models.IntegerField(default=0)),
                ('improvement', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_trends',
                'unique_together': {('user', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('threat_detection', 'Threat Detection'), ('incident_response', 'Incident Response'), ('risk_assessment', 'Risk Assessment'), ('communication', 'Communication Security'), ('navigation', 'Navigation Security')], max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('score', models.FloatField(default=0.0)),
                ('progress', models.FloatField(default=0.0)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_assessments',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
