# Generated by Django 5.2.8 on 2026-02-24 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('publish_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-publish_from'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'Content Category',
                'verbose_name_plural': 'Content Categories',
                'db_table': 'content_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('definition', models.TextField()),
                ('references', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='content.contentcategory')),
                ('related_terms', models.ManyToManyField(blank=True, to='content.glossaryterm')),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'verbose_name_plural': 'Glossary Terms',
                'db_table': 'glossary_terms',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('simulation', 'Simulation'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('link', 'External Link'), ('other', 'Other')], default='article', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_materials/')),
                ('video_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='material_images/')),
                ('estimated_read_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_materials', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
                'db_table': 'learning_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='path_thumbnails/')),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_paths', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='content.contentcategory')),
                ('materials', models.ManyToManyField(blank=True, related_name='learning_paths', to='content.learningmaterial')),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Bookmark',
                'verbose_name_plural': 'Material Bookmarks',
                'db_table': 'material_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.learningmaterial')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.materialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Comment',
                'verbose_name_plural': 'Material Comments',
                'db_table': 'material_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='content.learningmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Download',
                'verbose_name_plural': 'Material Downloads',
                'db_table': 'material_downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Like',
                'verbose_name_plural': 'Material Likes',
                'db_table': 'material_likes',
            },
        ),
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Progress',
                'verbose_name_plural': 'Material Progress Records',
                'db_table': 'material_progress',
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Rating',
                'verbose_name_plural': 'Material Ratings',
                'db_table': 'material_ratings',
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.learningmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material View',
                'verbose_name_plural': 'Material Views',
                'db_table': 'material_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_materials', models.JSONField(blank=True, default=list)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Path Enrollment',
                'verbose_name_plural': 'Path Enrollments',
                'db_table': 'path_enrollments',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='content.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Read',
                'verbose_name_plural': 'Announcement Reads',
                'db_table': 'announcement_reads',
                'unique_together': {('user', 'announcement')},
            },
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['category', 'is_published'], name='learning_ma_categor_a24ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['material_type', 'difficulty'], name='learning_ma_materia_140337_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['-created_at'], name='learning_ma_created_9d070b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialbookmark',
            unique_together={('user', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='materiallike',
            unique_together={('user', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='materialprogress',
            unique_together={('user', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='materialrating',
            unique_together={('user', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='pathenrollment',
            unique_together={('user', 'path')},
        ),
    ]
