# Generated by Django 6.0.5 on 2026-05-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_course_courseenrollment_coursecertificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecertificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
    ]
