# Generated by Django 5.2.8 on 2026-02-24 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('navigation', 'Navigation'), ('data_integrity', 'Data Integrity'), ('social_engineering', 'Social Engineering'), ('ransomware', 'Ransomware'), ('unauthorized_access', 'Unauthorized Access')], max_length=50)),
                ('threat_type', models.CharField(choices=[('jamming', 'Communication Jamming'), ('gps_spoofing', 'GPS Spoofing'), ('atc_access', 'Unauthorized ATC Access'), ('data_corruption', 'Data Corruption'), ('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('dos', 'Denial of Service'), ('man_in_middle', 'Man in the Middle')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('initial_state', models.JSONField(help_text='Initial scenario state')),
                ('steps', models.JSONField(help_text='Scenario steps and decision points')),
                ('correct_actions', models.JSONField(help_text='Expected correct actions')),
                ('hints', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='scenarios/thumbnails/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='scenarios/videos/')),
                ('supporting_docs', models.JSONField(blank=True, default=list)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('points_possible', models.IntegerField(default=100)),
                ('passing_score', models.IntegerField(default=70)),
                ('max_attempts', models.IntegerField(default=3)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('times_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('average_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_completion', 'First Completion'), ('perfect_score', 'Perfect Score'), ('speed_demon', 'Speed Demon'), ('no_hints', 'No Hints Used'), ('multiple_attempts', 'Persistent Learner')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_achievements',
            },
        ),
        migrations.CreateModel(
            name='ScenarioBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ScenarioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='simulations.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('difficulty_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='simulations.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_feedback',
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('session_state', models.JSONField(default=dict)),
                ('decisions', models.JSONField(default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('correct_choices', models.IntegerField(default=0)),
                ('total_choices', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('hints_used', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulations.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('decision_type', models.CharField(choices=[('choice', 'Multiple Choice'), ('action', 'Action'), ('response', 'Response'), ('escalation', 'Escalation')], max_length=20)),
                ('decision_data', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decisions', to='simulations.simulationsession')),
            ],
            options={
                'db_table': 'user_decisions',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['category'], name='scenarios_categor_e7005b_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['difficulty'], name='scenarios_difficu_3f055a_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['threat_type'], name='scenarios_threat__230bff_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['is_active'], name='scenarios_is_acti_8f4ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['is_featured'], name='scenarios_is_feat_1dde50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenarioachievement',
            unique_together={('user', 'scenario', 'achievement_type')},
        ),
        migrations.AlterUniqueTogether(
            name='scenariobookmark',
            unique_together={('user', 'scenario')},
        ),
        migrations.AlterUniqueTogether(
            name='scenariofeedback',
            unique_together={('user', 'scenario')},
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['user', '-started_at'], name='simulation__user_id_65a852_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['scenario'], name='simulation__scenari_ad8420_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['status'], name='simulation__status_6907e9_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['passed'], name='simulation__passed_fcc0b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationsession',
            unique_together={('user', 'scenario', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='userdecision',
            index=models.Index(fields=['session', 'step_number'], name='user_decisi_session_ea8bf2_idx'),
        ),
    ]
