# Generated by Django 5.2.8 on 2026-02-24 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('presentation', 'Presentation'), ('exercise', 'Exercise'), ('quiz', 'Quiz')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='tutor/materials/')),
                ('video_url', models.URLField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Material',
                'verbose_name_plural': 'Teaching Materials',
                'db_table': 'teaching_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.JSONField(default=list)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_meetings', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('default_meeting_duration', models.IntegerField(default=60)),
                ('default_max_participants', models.IntegerField(default=50)),
                ('allow_recording', models.BooleanField(default=True)),
                ('allow_chat', models.BooleanField(default=True)),
                ('allow_screen_share', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
                'db_table': 'tutor_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_type', models.CharField(choices=[('live', 'Live Session'), ('recorded', 'Recorded Session'), ('workshop', 'Workshop'), ('qanda', 'Q&A Session')], max_length=20)),
                ('platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('custom', 'Custom Link'), ('internal', 'Internal Meeting')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('max_attendees', models.IntegerField(default=50)),
                ('current_attendees', models.IntegerField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_sessions', to='meetings.meeting')),
                ('materials', models.ManyToManyField(blank=True, related_name='sessions', to='tutor.teachingmaterial')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor.tutorprofile')),
            ],
            options={
                'verbose_name': 'Teaching Session',
                'verbose_name_plural': 'Teaching Sessions',
                'db_table': 'teaching_sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='teachingmaterial',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tutor.tutorprofile'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_materials', models.JSONField(default=list)),
                ('completed_sessions', models.JSONField(default=list)),
                ('completed_exercises', models.JSONField(default=list)),
                ('attended_meetings', models.JSONField(default=list)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('tutor_notes', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_progress', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='tutor.tutorprofile')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progresses',
                'db_table': 'student_progress',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching'), ('scenario', 'Scenario Based')], max_length=20)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('explanations', models.JSONField(default=dict)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('passing_score', models.IntegerField(default=70)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tutor.tutorprofile')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('answers', models.JSONField()),
                ('time_taken', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutor.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Attempt',
                'verbose_name_plural': 'Exercise Attempts',
                'db_table': 'exercise_attempts',
                'unique_together': {('exercise', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tutor.teachingsession')),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'db_table': 'session_attendances',
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['tutor', 'start_time'], name='teaching_se_tutor_i_e6854b_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['session_type'], name='teaching_se_session_3e07e5_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingsession',
            index=models.Index(fields=['platform'], name='teaching_se_platfor_8725d4_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['tutor', '-created_at'], name='teaching_ma_tutor_i_2d2288_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['material_type'], name='teaching_ma_materia_8da7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['difficulty'], name='teaching_ma_difficu_ba998d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['is_published'], name='teaching_ma_is_publ_e08e3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('tutor', 'student')},
        ),
    ]
