# Generated by Django 4.2.7 on 2026-04-02 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('student_performance', 'Student Performance'), ('exercise_analytics', 'Exercise Analytics'), ('quarterly_review', 'Quarterly Review'), ('content_analysis', 'Content Analysis')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tutor/reports/')),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('generating', 'Generating')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tutor.tutorprofile')),
            ],
            options={
                'db_table': 'tutor_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
