# Generated by Django 4.2.7 on 2026-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Date by which the exercise should be completed', null=True),
        ),
    ]
