# Generated by Django 5.2.8 on 2026-02-24 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('meeting_type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group Session'), ('workshop', 'Workshop'), ('webinar', 'Webinar')], default='group', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('recorded', 'Recorded')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=50)),
                ('is_private', models.BooleanField(default=False)),
                ('require_host_to_start', models.BooleanField(default=True)),
                ('allow_recording', models.BooleanField(default=True)),
                ('allow_chat', models.BooleanField(default=True)),
                ('allow_screen_share', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('waiting_room_enabled', models.BooleanField(default=False)),
                ('lock_on_start', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_available', models.BooleanField(default=False)),
                ('participant_count', models.IntegerField(default=0)),
                ('peak_participants', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('private', 'Private')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='meetings.meeting')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_invitations',
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('participant', 'Participant'), ('observer', 'Observer')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('waiting', 'In Waiting Room'), ('joining', 'Joining'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('rejected', 'Rejected')], default='invited', max_length=20)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('peer_id', models.CharField(blank=True, max_length=255)),
                ('video_enabled', models.BooleanField(default=False)),
                ('audio_enabled', models.BooleanField(default=False)),
                ('screen_sharing', models.BooleanField(default=False)),
                ('video_state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('muted', 'Muted')], default='disabled', max_length=20)),
                ('audio_state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('muted', 'Muted')], default='disabled', max_length=20)),
                ('connection_quality', models.CharField(default='unknown', max_length=20)),
                ('ice_servers_used', models.JSONField(blank=True, default=dict)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_info', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('hand_raised', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_participants',
            },
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_code'], name='meetings_meeting_b1add0_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['room_name'], name='meetings_room_na_3b9994_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host', '-scheduled_start'], name='meetings_host_id_c37a86_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_start'], name='meetings_status_d69bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingchat',
            index=models.Index(fields=['meeting', '-created_at'], name='meeting_cha_meeting_8db8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinginvitation',
            index=models.Index(fields=['meeting', 'status'], name='meeting_inv_meeting_922e17_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinginvitation',
            index=models.Index(fields=['token'], name='meeting_inv_token_26954c_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'user'], name='meeting_par_meeting_d53d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'is_active'], name='meeting_par_meeting_7c1337_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['status'], name='meeting_par_status_253a2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user')},
        ),
    ]
