# Generated by Django 4.2.7 on 2026-02-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='tutor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='tutor.tutorprofile'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tutor_profile', '-scheduled_start'], name='meetings_tutor_p_39f3be_idx'),
        ),
    ]
